module.exports = {
  withEnvsAssurance: (
    /** @type {import('next').NextConfig} */
    nextConfig,
  ) => {
    const envKeys = [
      'NEXT_PUBLIC_ENV',
      'PORT',

      'NEXT_PUBLIC_CANONICAL_URL',

      'NEXT_PUBLIC_SHARETRIBE_SDK_CLIENT_ID',
      'SHARETRIBE_SDK_CLIENT_SECRET',
      'FLEX_INTEGRATION_CLIENT_ID',
      'FLEX_INTEGRATION_CLIENT_SECRET',

      'NEXT_PUBLIC_GOOGLE_MAPS_API_KEY',

      'SLACK_WEBHOOK_URL',
      'SLACK_WEBHOOK_ENABLED',

      'NEXT_APP_FIREBASE_PROJECT_ID',
      'NEXT_APP_FIREBASE_API_KEY',
      'NEXT_APP_FIREBASE_APP_ID',
      'NEXT_APP_FIREBASE_MEASURE_ID',
      'NEXT_APP_FIREBASE_MESSAGING_SENDER_ID',

      'FIREBASE_NOTIFICATION_COLLECTION_NAME',
      'FIREBASE_PAYMENT_RECORD_COLLECTION_NAME',
      'FIREBASE_PARTICIPANT_SUB_ORDER_COLLECTION_NAME',
      'FIREBASE_SUB_ORDER_CHANGES_HISTORY_COLLECTION_NAME',

      'NEXT_PUBLIC_GLEAP_SDK_KEY',

      'ONE_SIGNAL_APP_ID',
      'ONE_SIGNAL_API_KEY',

      'NEXT_APP_SCHEDULER_ACCESS_KEY',
      'NEXT_APP_SCHEDULER_SECRET_KEY',
      'ROLE_ARN',

      'SEND_FOOD_RATING_NOTIFICATION_LAMBDA_ARN',
      'TIME_TO_SEND_FOOD_RATING_NOTIFICATION',
      'SEND_REMIND_PICKING_NATIVE_NOTIFICATION_TO_BOOKER_LAMBDA_ARN',
      'AUTOMATIC_START_ORDER_JOB_LAMBDA_ARN',
      'PICK_FOOD_FOR_EMPTY_MEMBER_LAMBDA_ARN',
      'LAMBDA_ARN',

      'AWS_SES_ACCESS_KEY_ID',
      'AWS_SES_SECRET_ACCESS_KEY',
      'AWS_SES_REGION',
      'AWS_SES_SENDER_EMAIL',

      'NEXT_PUBLIC_MIXPANEL_ENABLED',
      'NEXT_PUBLIC_MIXPANEL_PROJECT_TOKEN',
      'NEXT_PUBLIC_MIXPANEL_DEBUG_ENABLED',

      'SENTRY_SOURCE_MAPS_ENABLED',
      'SENTRY_AUTH_TOKEN',
      'NEXT_PUBLIC_SENTRY_ENABLED',
      'NEXT_PUBLIC_SENTRY_ENVIRONMENT',

      'NEXT_PUBLIC_ORDER_MINIMUM_TIME',
      'NEXT_PUBLIC_PARTICIPANT_MINIMUM_SELECTION_TIME',
      'NEXT_PUBLIC_ORDER_AUTO_START_TIME_TO_DELIVERY_TIME_OFFSET_IN_HOUR',
    ];

    envKeys.forEach((key) => {
      if (!process.env[key]) {
        throw new Error(`Missing env variable ${key}`);
      }
    });

    return nextConfig;
  },
};
