version: 2
jobs:
  build:
    docker:
      - image: cimg/node:16.19.0
    steps:
      - setup_remote_docker:
          docker_layer_caching: false
      - checkout
      - run:
          name: Install AWS CLI
          command: curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && unzip awscliv2.zip && sudo ./aws/install -i /usr/local/aws-cli -b /usr/local/bin
      - run:
          name: Install jq
          command: sudo apt-get install jq
      - run:
          name: Copy Environment File
          command: ./scripts/ci_encode_environments.sh
      - run:
          name: Run deploy script
          command: ./scripts/deploy.sh

workflows:
  version: 2
  deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - production
