const NOTIFICATION_TYPES = {
  INVITATION: 'INVITATION',
  COMPANY_JOINED: 'COMPANY_JOINED',
  ORDER_SUCCESS: 'ORDER_SUCCESS',
  ORDER_CANCEL: 'ORDER_CANCEL',
  ORDER_DELIVERING: 'ORDER_DELIVERING',
  ORDER_PICKING: 'ORDER_PICKING',
  ORDER_RATING: 'ORDER_RATING',

  SUB_ORDER_UPDATED: 'SUB_ORDER_UPDATED',
  SUB_ORDER_INPROGRESS: 'SUB_ORDER_INPROGRESS',
  SUB_ORDER_CANCELED: 'SUB_ORDER_CANCELED',
  SUB_ORDER_DELIVERED: 'SUB_ORDER_DELIVERED',
  SUB_ORDER_DELIVERING: 'SUB_ORDER_DELIVERING',
  SUB_ORDER_REVIEWED_BY_BOOKER: 'SUB_ORDER_REVIEWED_BY_BOOKER',
  SUB_ORDER_REVIEWED_BY_PARTICIPANT: 'SUB_ORDER_REVIEWED_BY_PARTICIPANT',
  PARTNER_MENU_CREATED_BY_ADMIN: 'PARTNER_MENU_CREATED_BY_ADMIN',
  PARTNER_FOOD_CREATED_BY_ADMIN: 'PARTNER_FOOD_CREATED_BY_ADMIN',
  PARTNER_PROFILE_UPDATED_BY_ADMIN: 'PARTNER_PROFILE_UPDATED_BY_ADMIN',
};
module.exports = { NOTIFICATION_TYPES };
