const EmailTemplateForBookerTypes = {
  BOOKER_ACCOUNT_CREATED: 'BOOKER_ACCOUNT_CREATED',
  BOOKER_ACCOUNT_SUSPENDED: 'BOOKER_ACCOUNT_SUSPENDED',
  BOOKER_ORDER_CREATED: 'BOOKER_ORDER_CREATED',
  BOOKER_ORDER_PICKING: 'BOOKER_ORDER_PICKING',
  BOOKER_ORDER_SUCCESS: 'BOOKER_ORDER_SUCCESS',
  BOOKER_SUB_ORDER_CANCELED: 'BOOKER_SUB_ORDER_CANCELED',
  BOOKER_REVENUE_ANALYTICS: 'BOOKER_REVENUE_ANALYTICS',
  BOOKER_ORDER_CANCELLED: 'BOOKER_ORDER_CANCELLED',
  BOOKER_PICKING_ORDER_CHANGED: 'BOOKER_PICKING_ORDER_CHANGED',
};

const EmailTemplateForParticipantTypes = {
  PARTICIPANT_COMPANY_INVITATION: 'PARTICIPANT_COMPANY_INVITATION',
  PARTICIPANT_ORDER_PICKING: 'PARTICIPANT_ORDER_PICKING',
  PARTICIPANT_SUB_ORDER_CANCELED: 'PARTICIPANT_SUB_ORDER_CANCELED',
  PARTICIPANT_PICKING_ORDER_CHANGED: 'PARTICIPANT_PICKING_ORDER_CHANGED',
};

const EmailTemplateForPartnerTypes = {
  PARTNER_NEW_ORDER_APPEAR: 'PARTNER_NEW_ORDER_APPEAR',
  PARTNER_SUB_ORDER_CANCELED: 'PARTNER_SUB_ORDER_CANCELED',
  PARTNER_ORDER_DETAILS_UPDATED: 'PARTNER_ORDER_DETAILS_UPDATED',
};

const EmailTemplateTypes = {
  BOOKER: EmailTemplateForBookerTypes,
  PARTICIPANT: EmailTemplateForParticipantTypes,
  PARTNER: EmailTemplateForPartnerTypes,
};

module.exports = {
  EmailTemplateForBookerTypes,
  EmailTemplateForParticipantTypes,
  EmailTemplateForPartnerTypes,
  EmailTemplateTypes,
};
