declare namespace NodeJS {
  export interface ProcessEnv {
    NEXT_PUBLIC_ENV: 'development' | 'staging' | 'production';
    PORT: string;
    PITO_ADMIN_ID: string;

    NEXT_PUBLIC_CANONICAL_URL: string;

    NEXT_PUBLIC_SHARETRIBE_SDK_CLIENT_ID: string;
    SHARETRIBE_SDK_CLIENT_SECRET: string;
    FLEX_INTEGRATION_CLIENT_ID: string;
    FLEX_INTEGRATION_CLIENT_SECRET: string;
    NEXT_PUBLIC_CHANGE_STRUCTURE_TX_PROCESS_VERSION: string;

    SUB_ACCOUNT_EMAIL: string;
    FLEX_CONSOLE_LOGIN_STRING: string;
    FLEX_CONSOLE_INTERNAL_API_SERVER_URL: string;
    FLEX_CONSOLE_MARKETPLACE_ENVIRONMENT: string;

    NEXT_PUBLIC_GOOGLE_MAPS_API_KEY: string;

    SLACK_WEBHOOK_URL: string;
    SLACK_WEBHOOK_ENABLED: 'true' | 'false';

    NEXT_APP_FIREBASE_PROJECT_ID: string;
    NEXT_APP_FIREBASE_API_KEY: string;
    NEXT_APP_FIREBASE_APP_ID: string;
    NEXT_APP_FIREBASE_MEASURE_ID: string;
    NEXT_APP_FIREBASE_MESSAGING_SENDER_ID: string;

    FIREBASE_NOTIFICATION_COLLECTION_NAME: string;
    FIREBASE_PAYMENT_RECORD_COLLECTION_NAME: string;
    FIREBASE_PARTICIPANT_SUB_ORDER_COLLECTION_NAME: string;
    FIREBASE_SUB_ORDER_CHANGES_HISTORY_COLLECTION_NAME: string;
    FIREBASE_ORDER_CHANGES_HISTORY_COLLECTION_NAME: string;

    ENCRYPT_PASSWORD_SECRET_KEY: string;

    EXTERNAL_API_KEY_SALT: string;

    NEXT_PUBLIC_IMPORT_FOOD_GUIDE_FILE_URL: string;
    NEXT_PUBLIC_IMPORT_FOOD_TEMPLATE: string;
    NEXT_PUBLIC_EMAIL_TEMPLATE_FILE_URL: string;

    NEXT_PUBLIC_GLEAP_SDK_KEY: string;

    ONE_SIGNAL_APP_ID: string;
    ONE_SIGNAL_API_KEY: string;

    NEXT_APP_SCHEDULER_ACCESS_KEY: string;
    NEXT_APP_SCHEDULER_SECRET_KEY: string;
    ROLE_ARN: string;

    SEND_FOOD_RATING_NOTIFICATION_LAMBDA_ARN: string;
    TIME_TO_SEND_FOOD_RATING_NOTIFICATION: string;
    SEND_REMIND_PICKING_NATIVE_NOTIFICATION_TO_BOOKER_LAMBDA_ARN: string;
    AUTOMATIC_START_ORDER_JOB_LAMBDA_ARN: string;
    PICK_FOOD_FOR_EMPTY_MEMBER_LAMBDA_ARN: string;
    LAMBDA_ARN: string;

    AWS_SES_ACCESS_KEY_ID: string;
    AWS_SES_SECRET_ACCESS_KEY: string;
    AWS_SES_REGION: string;
    AWS_SES_SENDER_EMAIL: string;

    NEXT_PUBLIC_MIXPANEL_PROJECT_TOKEN: string;
    NEXT_PUBLIC_MIXPANEL_ENABLED: 'true' | 'false';
    NEXT_PUBLIC_MIXPANEL_DEBUG_ENABLED: 'true' | 'false';

    SENTRY_SOURCE_MAPS_ENABLED: 'true' | 'false';
    SENTRY_AUTH_TOKEN: string;
    NEXT_PUBLIC_SENTRY_ENVIRONMENT: 'development' | 'staging' | 'production';
    NEXT_PUBLIC_SENTRY_ENABLED: 'true' | 'false';

    NEXT_PUBLIC_ORDER_MINIMUM_TIME: string;
    NEXT_PUBLIC_PARTICIPANT_MINIMUM_SELECTION_TIME: string;
    NEXT_PUBLIC_ORDER_AUTO_START_TIME_TO_DELIVERY_TIME_OFFSET_IN_HOUR: string;
    NEXT_PUBLIC_DISTANCE_LIMIT_KILOMETERS: string;
    NEXT_PUBLIC_MAX_KILOMETER_FROM_RESTAURANT_TO_DELIVERY_ADDRESS_FOR_BOOKER: string;
    NEXT_PUBLIC_REMIND_PICKING_NATIVE_NOTIFICATION_TO_BOOKER_TIME_TO_DEADLINE_IN_MINUTES: string;
    NEXT_PUBLIC_SEND_REMIND_PICKING_ORDER_TIME_TO_DEADLINE_IN_MINUTES: string;
  }
}
