declare namespace NodeJS {
  export interface ProcessEnv {
    ONE_SIGNAL_APP_ID: string;
    ONE_SIGNAL_API_KEY: string;

    NEXT_APP_FIREBASE_PROJECT_ID: string;
    NEXT_APP_FIREBASE_API_KEY: string;
    NEXT_APP_FIREBASE_APP_ID: string;
    NEXT_APP_FIREBASE_MEASURE_ID: string;
    NEXT_APP_FIREBASE_MESSAGING_SENDER_ID: string;

    FIREBASE_NOTIFICATION_COLLECTION_NAME: string;
    FIREBASE_PAYMENT_RECORD_COLLECTION_NAME: string;
    FIREBASE_PARTICIPANT_SUB_ORDER_COLLECTION_NAME: string;
    FIREBASE_SUB_ORDER_CHANGES_HISTORY_COLLECTION_NAME: string;

    SEND_FOOD_RATING_NOTIFICATION_LAMBDA_ARN: string;
    TIME_TO_SEND_FOOD_RATING_NOTIFICATION: string;

    AWS_SES_ACCESS_KEY_ID: string;
    AWS_SES_SECRET_ACCESS_KEY: string;
    AWS_SES_REGION: string;
    AWS_SES_SENDER_EMAIL: string;

    NEXT_PUBLIC_MIXPANEL_PROJECT_TOKEN: string;
    NEXT_PUBLIC_MIXPANEL_ENABLED: 'true' | 'false';
    NEXT_PUBLIC_MIXPANEL_DEBUG_ENABLED: 'true' | 'false';

    SENTRY_SOURCE_MAPS_ENABLED: 'true' | 'false';
    SENTRY_AUTH_TOKEN: string;
    NEXT_PUBLIC_SENTRY_ENVIRONMENT: 'development' | 'staging' | 'production';
    NEXT_PUBLIC_SENTRY_ENABLED: 'true' | 'false';
  }
}
