#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

yarn lint-staged

echo '🤔🤔🤔🤔... Alright... Code looks good to me... Trying to build now. 🤔🤔🤔🤔'

yarn build ||
(
    echo '❌👷🔨❌ Better call Chu... Because your build failed ❌👷🔨❌
            Next build failed: View the errors above to see why. 
    '
    false;
)

echo '✅✅✅✅ You win this time... I am committing this now. ✅✅✅✅'
