name: Production Deployment
on:
  push:
    tags:
      - "v*"

jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Push to Production
        run: git push origin HEAD:production --force
